### ISSUE TITLE
Readme incorrectly lists linux local dumping as if it were supported

### ISSUE THREAD

**Issue by kkartaltepe** [rust-minidump/minidump-writer#102]
For some reason the readme lists a "local process" [example](https://github.com/rust-minidump/minidump-writer?tab=readme-ov-file#local-process) as if it were supported. We can see its not by copying the example code into a rust program's main and executing.

The minidump will fail with `failed to write minidump: DumperError(SuspendNoThreadsLeft(1))` and if we look at the dumping code we can see it depends on ptrace-ing. Since ptrace hasnt supported self attachment since 2005 its unlikely this particular dumping code ever worked, maybe there used to be a local dumper that was removed but without removing the readme component.

**Comment by Jake-Shadle** [comment]
b687584
