### ISSUE TITLE
MacOS follow up

### ISSUE THREAD

**Issue by Jake-Shadle** [rust-minidump/minidump-writer#23]
#21 adds MacOS support but while testing I noticed a few things that _might_ be improved, though it's hard to say given the embarrassing state of Apple's documentation. Writing this down now so I don't forget later.

- Minidump supports thread names, however the MacOS implementation doesn't write that data, because Breakpad doesn't. This _might_ (again, terrible documentation) be impossible since the thread name is actually part of pthreads, but on the minidump-writer side we are working with mach ports which are (mostly?) paired with a pthread, but AFAICT the API to retrieve the thread name for the pthread is task specific and probably won't work? But this would be extremely nice information to have if we can get it reliably. There might be some shenanigans to be done by finding out where the BSD pthread info is located in the process space and just reading it directly from the process memory like we do with eg the thread stack etc.

**Comment by gabrielesvelto** [comment]
We've already implemented this in Breakpad, see: https://hg.mozilla.org/mozilla-central/rev/63e43c6f4114

Porting it should be straightforward.
