### ISSUE TITLE
Remove `windows-sys` dependency

### ISSUE THREAD

**Issue by Jake-Shadle** [rust-minidump/minidump-writer#58]
`windows-sys` is still moving far too quickly resulting in churn and duplicate dependencies, the usage in this crate is quite limited, so it makes sense to just bite the bullet and handwrite the binding we actually need and remove the dependency so that downstream crates don't have to care which version of windows-sys they may use.

**Comment by gabrielesvelto** [comment]
You might want to cherry-pick https://github.com/mozilla/minidump-writer/commit/951d2d866b14e7d40863796082c50b1f8b0237e3
