### ISSUE TITLE
Evaluate writing out a MemoryInfoListStream

### ISSUE THREAD

**Issue by gabrielesvelto** [rust-minidump/minidump-writer#8]
To improve stack walking heuristics we'd like to validate ambiguous instruction pointers by checking if they fall within an executable reason. On Windows this is already possible because **windbg.dll** populates the `MemoryInfoListStream` with the whole state of the process' memory when it snapshots it. On Linux we currently have `/proc/self/maps` which contains the required information but we'd have to parse it in the stackwalker to yield the same information. Alternatively we might try and populate the `MemoryInfoListStream` on Linux too in order to be able to use the same code across different platforms.

Populating the stream should be relatively simple, info regarding the [header](https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/ns-minidumpapiset-minidump_memory_info_list) and [entries](https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/ns-minidumpapiset-minidump_memory_info) are readily available. The biggset issue is that the `AllocationProtect`, `State`, `Protect` and `Type` fields are supposed to contain Windows-specific constants. There's two ways to tackle this: either we use those fields to store Linux-specific constants - but that would defeat the purpose of having identical code for all platforms in the stack walker - or we map them to their closest Windows equivalents. Interestingly crashpad does the latter for [fuchsia](https://chromium.googlesource.com/crashpad/crashpad/+/d8f60c81124fd2a9f3e64e59c0ae2a18e6700a12/snapshot/fuchsia/memory_map_region_snapshot_fuchsia.cc#26) but it does not populate the stream on Linux and macOS.

**Comment by luser** [comment]
If someone writes a useful parser for `maps` you could just reuse the same implementation in this crate + the stackwalker. :)

**Comment by afranchuk** [comment]
@luser Would `minidump-common` be an okay common place for the `maps` parser? Or should it be a separate crate entirely?

**Comment by luser** [comment]
That doesn't quite feel like the right place for it, since currently `minidump-common` is mostly type definitions.

n.b.: @Gankra implemented stackwalker parsing of this along with a unified interface atop that + `MemoryInfoListStream` in https://github.com/rust-minidump/rust-minidump/pull/268 . See also https://github.com/rust-minidump/rust-minidump/issues/256

**Comment by afranchuk** [comment]
I agree, I was asking on the off-chance that others didn't agree with my thought and it'd be simpler :)

Thanks for the info, I was aware of the existing impl. I was just going to move it somewhere common and maybe slightly clean up the interface so that it could be used in minidump-writer!

**Comment by afranchuk** [comment]
Any suggestion on crate name/location? Alternatively, maybe we could contribute to the `procfs` crate and expose its `process::MemoryMap::from_line()` implementation?

**Comment by gabrielesvelto** [comment]
Contributing to an external crate sounds like a good idea if the crate is sufficiently widespread and useful. We parse `/proc` files in a lot of places within Firefox code and the `procfs` crate sounds like something we'll end up using eventually.

**Comment by afranchuk** [comment]
The `procfs` team seems [open to contribution](https://github.com/eminence/procfs/issues/236) along these lines, so that is probably the path to follow.

**Comment by gabrielesvelto** [comment]
> The `procfs` team seems [open to contribution](https://github.com/eminence/procfs/issues/236) along these lines, so that is probably the path to follow.

Excellent!

**Comment by afranchuk** [comment]
I'm currently waiting (patiently, there's no rush) for `procfs` to tag a new version. Then this can proceed.

**Comment by eminence** [comment]
`procfs` maintainer here :wave:  To set some rough expectations, I'm going to try to get a new release of `procfs` out within a week.   Thanks to @afranchuk who did the implementation within `procfs`

**Comment by afranchuk** [comment]
@eminence thanks for chiming in with an update! I will set a reminder to check on things in a week.
