### ISSUE TITLE
New release for minidump-common 0.9

### ISSUE THREAD

**Issue by Ninja3047** [rust-minidump/minidump-writer#95]
Since [rust-minidump 0.9](https://github.com/rust-minidump/rust-minidump/releases/tag/v0.19.1) has been released, it would be nice if a new version of this crate could be released as well so the newer 0.9 version can be used with this crate since the dependency has already been updated [here](https://github.com/rust-minidump/minidump-writer/commit/8cbca269a71a2e40c060718c1876d9c1044b7158).

**Comment by gabrielesvelto** [comment]
We're waiting on the merge of PR https://github.com/rust-minidump/minidump-writer/pull/90 and then we'll cut a new release.

**Comment by Jake-Shadle** [comment]
https://github.com/rust-minidump/minidump-writer/releases/tag/0.8.3

**Comment by gabrielesvelto** [comment]
Thanks!
